services:
  my-helper-db:
    container_name: myhelper_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  my-helper-server:
    restart: unless-stopped
    container_name: my-helper-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      my-helper-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 3000:8000
    volumes:
      - ./:/app
    command:
      - sh
      - -c
      - 'python src/manage.py migrate && 
         python src/manage.py shell -c
        "from django.contrib.auth import get_user_model;
         User = get_user_model();
         User.objects.filter(username=\"${DJANGO_ADMIN}\").exists() or User.objects.create_superuser(\"${DJANGO_ADMIN}\", \"${DJANGO_EMAIL}\", \"${DJANGO_PASSWORD}\")" &&
         python src/manage.py runserver 0.0.0.0:8000'

volumes:
  postgres_data: